### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by zamus1** [loduis/alegra-php#1]
When i try to execute the following command:

composer require loduis/alegra-php

I get this error message:Problem 1
    - Installation request for loduis/alegra-php 1.0.* -> satisfiable by loduis/alegra-php[1.0.x-dev].
    - loduis/alegra-php 1.0.x-dev requires loduis/illuminate-api 1.0.* -> no matching package found.

**Comment by loduis** [comment]
Hi,
You need try composer require "loduis/alegra-php:@dev"
The package is dev minimum-stability

Your composer.json file
```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "loduis/alegra-php": "1.0.*"
    }
}
```

**Comment by zamus1** [comment]
Thanks loduis!

I can confirm it works! 

I was able to install your library.

Thank you very much!
